- hosts: all
  
  tasks:
   
   - name: Generate hosts file
     lineinfile: dest=/etc/hosts
                 regexp='.*{{ item }}$'
                 line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}}"
                 state=present            
     when: hostvars[item].ansible_default_ipv4.address is defined
     with_items: "{{groups['all']}}"
     become: true
     
   #- name: Set hostname
   #  hostname: name="{{inventory_hostname}}"
   #  become: true

   - name: apt update
     apt: update_cache=yes upgrade=dist
     become: true

   - name: Copy SSH private key to remote
     become: true
     copy:
       src: /home/ubuntu/.ssh/id_ed25519    
       dest: /home/appuser/.ssh/id_ed25519
       owner: appuser
       group: appuser
       mode: '0600'

   - name: Clone private GitHub repo using SSH
     become: true
     git:
       repo: 'git@github.com:AppleShay/DEII-Stargazers.git'
       dest: /DEII-Stargazers 
       key_file: /home/appuser/.ssh/id_ed25519
       accept_hostkey: yes

   - name: Fix permissions of cloned project
     become: true
     file:
       path: /modeltraining
       owner: appuser
       group: appuser
       recurse: yes

- hosts: prodserver
 
  vars_files:
   - setup_var.yml  
  
  tasks:  
   - name: Extra packages
     apt: pkg={{item}} state=latest update_cache=true 
     with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
     become: true  

   - name: apt update
     apt: update_cache=yes upgrade=dist
     become: true

   - name: Add Docker repository key
     apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
     become: true

   - name: Add Docker repository 
     command: add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
     become: true

   - name: apt update
     apt: update_cache=yes upgrade=dist
     become: true
  
   # Workaround pip issue with MTU mismatch, see: https://github.com/docker/docker.github.io/pull/9249/files
   # MTU for SNIC is 1450, Docker default is 1500. Override so that Docker matches the host.
   # We create the config file before installing, to avoid any need to restart the docker daemon.
   - name: Create Ansible docker config directory.
     become: true
     file:
       path: "/etc/docker"
       state: directory

   - name: Create Ansible docker file to configure Docker MTU to match SNIC for pip issue
     become: true
     copy:
       dest: "/etc/docker/daemon.json"
       content: |
        {
          "mtu": 1450
        }

   - name: Install Docker  
     apt: pkg=docker-ce state=present update_cache=true allow_unauthenticated=yes
     become: true

   - name: Running containers
     become: true
     shell: docker compose up -d 
     args: 
      chdir: /DEII-Stargazers/app/githubstar/production_server

- hosts: devserver
  
  vars_files:
   - setup_var.yml

  tasks:
   - name: Extra packages
     apt: pkg=python3-pip state=latest update_cache=true  
     become: true

   - name: Install ML packages
     become: true
     pip: 
      name: 
          - scikit-learn==1.6.1
          - xgboost==3.0.1
          - tensorflow==2.10.0
          - keras==2.10.0
          - lightgbm==4.6.0
          - numpy==2.2.6
          - scipy==1.15.3
          - pandas==2.2.3
          - joblib==1.5.0
          - future
          - threadpoolctl==3.6.0
          - six==1.17.0
          - packaging==25.0
