name: Docker CI for Star Predictor

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v3

    - name: 🛠️ Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: 🧱 Build Docker image
      run: docker build -t star-predictor ./app/github

    - name: 🚀 Run container
      run: docker run -d --name star-app -p 5100:5100 star-predictor

    - name: ✅ Health check (wait for container to start)
      run: |
        for i in {1..10}; do
          echo "Checking if app is up (try $i)..."
          if curl -s http://localhost:5100 | grep -q "GitHub Repo Star Predictor"; then
            echo "App is healthy ✅"
            exit 0
          fi
          sleep 3
        done
        echo "❌ App failed to start in time"
        docker logs star-app
        exit 1
