- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Ensure Docker is running
  service:
    name: docker
    state: started
    enabled: true

- name: Pull star predictor image
  command: docker pull appleshay/star-predictor:latest

- name: Run the container
  command: docker run -d --name star-predictor -p 5000:5000 appleshay/star-predictor:latest
  ignore_errors: true  # Optional: to avoid failing if already running
